### ISSUE TITLE
Tasker 初始化失败，资源 clean up 时：Tasker' object has no attribute 'terminate'

### ISSUE THREAD

**Issue by yyhran** [TanyaShue/MaaYYs#3]
tasker初始化失败资源 clear up 时报错：Tasker' object has no attribute 'terminate'，看了下 Tasker 并没有 terminate 方法
```shell
ERROR:root:Error initializing tasker for D:\leidian\LDPlayer9\adb.exe:127.0.0.1:5555: Failed to initialize MAA tasker.
INFO:root:Cleaning up resources for D:\leidian\LDPlayer9\adb.exe:127.0.0.1:5555
ERROR:root:Error during cleanup for D:\leidian\LDPlayer9\adb.exe:127.0.0.1:5555: 'Tasker' object has no attribute 'terminate'
INFO:root:Tasker thread for D:\leidian\LDPlayer9\adb.exe:127.0.0.1:5555 has been terminated.
```
https://github.com/TanyaShue/MaaYYs/blob/601f2b39ee7edab2947bdde76f7888e2dc6bf395/src/core/tasker_thread.py#L128-L129

**Comment by yyhran** [comment]
即使该任务失败，页面上仍显示“正在运行”
![QQ_1731202105214](https://github.com/user-attachments/assets/4858a879-1159-4d04-a018-2a9728713f39)
感觉是否可以提供一个回调处理任务失败的情况

**Comment by TanyaShue** [comment]
待会修一下

**Comment by TanyaShue** [comment]
已修复
