### ISSUE TITLE
一些随便的讨论

### ISSUE THREAD

**Issue by TanyaShue** [TanyaShue/MaaYYs#5]
由于pyside6和maafw不兼容,所以我现在只能使用前后端分离的做法,这样显得程序很臃肿,不知道有没有更好的做法,

还有就是启动选项中启动游戏的start app中各个地方下载的版本的启动activity不同,没办法做到统一,

现在当启动多个程序时主要启动的是多线程来处理,当启动的比较多时,(比如我是三个),似乎会出现混乱,具体原因未知,我在想这种同时处理多个模拟器控制的时候改为使用多进程来处理是否会更好一点

**Comment by yyhran** [comment]
pyside6和maafw不兼容是指这里讨论的问题吗 https://github.com/MaaXYZ/MaaFramework/issues/361 最开始我也遇到了这个问题，也是靠拷贝 `C:\Windows\System32` 下的文件到 maafw 的 dll 目录下解决的。后来发现可能是 Anaconda 的锅，因为后面换成 miniconda 之后 pyside6 和 maafw 的 import 顺序不同也不会出问题了；另一台机器上用 miniforge 环境也没这个问题。

目前还没多开使用过，不知道这里的混乱是什么情况，但是感觉使用多进程会比较麻烦一点

**Comment by TanyaShue** [comment]
好像还真是Anaconda 的锅,换成miniconda 好像就行了,不过想想现在这样也还行,前后端分开可以方便之后做远程连接

**Comment by TanyaShue** [comment]
嗯,所以我准备了个监控api端口

**Comment by TanyaShue** [comment]
等有时间实现一下
